collections_config:
  staff_members:
    icon: account_circle
    disable_url: false
    _enabled_editors:
      - data
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: schemas/staff_members.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        icon: notes
  products:
    icon: shopping_cart
    disable_url: false
    _enabled_editors:
      - data
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: schemas/products.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        icon: notes
_inputs:
  map:
    comment: Update the map location and display settings.
    cascade: true
  latitude:
    comment: Coordinates for the center marker on the map.
    cascade: true
  longitude:
    comment: Coordinates for the center marker on the map.
    cascade: true
  zoom:
    comment: The zoom level for the map.
    cascade: true
  pricing_table:
    comment: Update the information in the pricing tables.
    cascade: true
  highlight:
    comment: Emphasis the text
    cascade: true
  color:
    comment: The background color used in the plan name and call to action.
    cascade: true
  new_window:
    comment: Open link in new window
    cascade: true
  description:
    comment: This is used for facebook shares of the page and google indexing
    cascade: true
_select_data:
  garment_types:
    - hat
    - top
timezone: Etc/UTC
